In [1]:
import duckdb
import pandas as pd
conn = duckdb.connect('../datasets/db/adventureworks.duckdb')

# 1. Data Cleaning

## 1. Tables Overview

In [28]:
conn.execute("SHOW TABLES").fetchdf()

                           name
0               calendar_lookup
1               customer_lookup
2     product_categories_lookup
3                product_lookup
4  product_subcategories_lookup
5                  returns_data
6                    sales_2020
7                    sales_2021
8                    sales_2022
9              territory_lookup

In [29]:
qry = """ 
    SELECT 'calendar_lookup' AS table_name, COUNT(*) AS row_count FROM calendar_lookup
    UNION ALL SELECT 'customer_lookup' AS table_name, COUNT(*) AS row_count FROM customer_lookup
    UNION ALL SELECT 'product_categories_lookup' AS table_name, COUNT(*) AS row_count FROM product_categories_lookup
    UNION ALL SELECT 'product_lookup' AS table_name, COUNT(*) AS row_count FROM product_lookup
    UNION ALL SELECT 'product_subcategories_lookup' AS table_name, COUNT(*) AS row_count FROM product_subcategories_lookup
    UNION ALL SELECT 'returns_data' AS table_name, COUNT(*) AS row_count FROM returns_data
    UNION ALL SELECT 'sales_2021' AS table_name, COUNT(*) AS row_count FROM sales_2021
    UNION ALL SELECT 'sales_2022' AS table_name, COUNT(*) AS row_count FROM sales_2022
    UNION ALL SELECT 'territory_lookup' AS table_name, COUNT(*) AS row_count FROM territory_lookup
ORDER BY table_name;
"""
conn.execute(qry).fetch_df()

                     table_name  row_count
0               calendar_lookup        912
1               customer_lookup      18154
2     product_categories_lookup          4
3                product_lookup        293
4  product_subcategories_lookup         37
5                  returns_data       1809
6                    sales_2021      23935
7                    sales_2022      29481
8              territory_lookup         10

## 1. Missing Data

In [38]:
qry = """ 
    DROP TABLE IF EXISTS territory_lookup;
"""

conn.execute(qry).fetch_df()

Empty DataFrame
Columns: [Success]
Index: []

In [39]:
qry = """ 
    CREATE OR REPLACE TABLE territory_lookup AS 
    SELECT * 
    FROM read_csv_auto(
        '../datasets/raw/AdventureWorks Territory Lookup.csv',
        delim=',',
        header=true,
        encoding='utf-8',
        ignore_errors=true,  -- Skip bad rows
        normalize_names=true  -- Auto-clean nama kolom (hapus spasi, full-width?)
    );
"""

conn.execute(qry).fetch_df()

   Count
0     10

In [40]:
qry = """ 
    DESCRIBE territory_lookup;
"""

conn.execute(qry).fetch_df()

         column_name column_type null   key default extra
0  salesterritorykey      BIGINT  YES  None    None  None
1             region     VARCHAR  YES  None    None  None
2            country     VARCHAR  YES  None    None  None
3          continent     VARCHAR  YES  None    None  None